# CSV
---

Un archivo de valores separados por comas (CSV) es un archivo de texto delimitado que utiliza una coma para separar valores. 

Cada línea del archivo es un registro de datos. 

Cada registro consta de uno o más campos, separados por comas.


Haremos un ejemplo de como cargar el archvio CSV, es este caso usaremos las opciones por defecto.

In [3]:
from langchain.document_loaders.csv_loader import CSVLoader

loader = CSVLoader(
    file_path="../../example_data/mlb_teams_2012.csv"
)
data = loader.load()

Veamos el contenido del documento

In [4]:
print(data)

[Document(page_content='Team: Nationals\n"Payroll (millions)": 81.34\n"Wins": 98', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 0}), Document(page_content='Team: Reds\n"Payroll (millions)": 82.20\n"Wins": 97', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 1}), Document(page_content='Team: Yankees\n"Payroll (millions)": 197.96\n"Wins": 95', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 2}), Document(page_content='Team: Giants\n"Payroll (millions)": 117.62\n"Wins": 94', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 3}), Document(page_content='Team: Braves\n"Payroll (millions)": 83.31\n"Wins": 94', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 4}), Document(page_content='Team: Athletics\n"Payroll (millions)": 55.37\n"Wins": 94', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 5}), Document(page_content='Team: Rangers\n"Payroll (millions)": 120.51\n"Wins": 93', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 6}), Document(page_content='Team: Orioles\n"Payroll (millions)": 81.43\n"Wins": 93', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 7}), Document(page_content='Team: Rays\n"Payroll (millions)": 64.17\n"Wins": 90', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 8}), Document(page_content='Team: Angels\n"Payroll (millions)": 154.49\n"Wins": 89', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 9}), Document(page_content='Team: Tigers\n"Payroll (millions)": 132.30\n"Wins": 88', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 10}), Document(page_content='Team: Cardinals\n"Payroll (millions)": 110.30\n"Wins": 88', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 11}), Document(page_content='Team: Dodgers\n"Payroll (millions)": 95.14\n"Wins": 86', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 12}), Document(page_content='Team: White Sox\n"Payroll (millions)": 96.92\n"Wins": 85', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 13}), Document(page_content='Team: Brewers\n"Payroll (millions)": 97.65\n"Wins": 83', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 14}), Document(page_content='Team: Phillies\n"Payroll (millions)": 174.54\n"Wins": 81', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 15}), Document(page_content='Team: Diamondbacks\n"Payroll (millions)": 74.28\n"Wins": 81', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 16}), Document(page_content='Team: Pirates\n"Payroll (millions)": 63.43\n"Wins": 79', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 17}), Document(page_content='Team: Padres\n"Payroll (millions)": 55.24\n"Wins": 76', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 18}), Document(page_content='Team: Mariners\n"Payroll (millions)": 81.97\n"Wins": 75', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 19}), Document(page_content='Team: Mets\n"Payroll (millions)": 93.35\n"Wins": 74', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 20}), Document(page_content='Team: Blue Jays\n"Payroll (millions)": 75.48\n"Wins": 73', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 21}), Document(page_content='Team: Royals\n"Payroll (millions)": 60.91\n"Wins": 72', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 22}), Document(page_content='Team: Marlins\n"Payroll (millions)": 118.07\n"Wins": 69', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 23}), Document(page_content='Team: Red Sox\n"Payroll (millions)": 173.18\n"Wins": 69', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 24}), Document(page_content='Team: Indians\n"Payroll (millions)": 78.43\n"Wins": 68', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 25}), Document(page_content='Team: Twins\n"Payroll (millions)": 94.08\n"Wins": 66', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 26}), Document(page_content='Team: Rockies\n"Payroll (millions)": 78.06\n"Wins": 64', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 27}), Document(page_content='Team: Cubs\n"Payroll (millions)": 88.19\n"Wins": 61', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 28}), Document(page_content='Team: Astros\n"Payroll (millions)": 60.65\n"Wins": 55', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 29})]

Usaremos pandas, para mostrar de mejor forma como fue cargado el documento

In [13]:
import pandas as pd

pd.set_option("max.colwidth", None)
df = pd.DataFrame(data)
df

,0,1
0,"(page_content, Team: Nationals\n""Payroll (millions)"": 81.34\n""Wins"": 98)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 0})"
1,"(page_content, Team: Reds\n""Payroll (millions)"": 82.20\n""Wins"": 97)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 1})"
2,"(page_content, Team: Yankees\n""Payroll (millions)"": 197.96\n""Wins"": 95)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 2})"
3,"(page_content, Team: Giants\n""Payroll (millions)"": 117.62\n""Wins"": 94)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 3})"
4,"(page_content, Team: Braves\n""Payroll (millions)"": 83.31\n""Wins"": 94)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 4})"
5,"(page_content, Team: Athletics\n""Payroll (millions)"": 55.37\n""Wins"": 94)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 5})"
6,"(page_content, Team: Rangers\n""Payroll (millions)"": 120.51\n""Wins"": 93)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 6})"
7,"(page_content, Team: Orioles\n""Payroll (millions)"": 81.43\n""Wins"": 93)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 7})"
8,"(page_content, Team: Rays\n""Payroll (millions)"": 64.17\n""Wins"": 90)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 8})"
9,"(page_content, Team: Angels\n""Payroll (millions)"": 154.49\n""Wins"": 89)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 9})"
10,"(page_content, Team: Tigers\n""Payroll (millions)"": 132.30\n""Wins"": 88)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 10})"
11,"(page_content, Team: Cardinals\n""Payroll (millions)"": 110.30\n""Wins"": 88)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 11})"
12,"(page_content, Team: Dodgers\n""Payroll (millions)"": 95.14\n""Wins"": 86)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 12})"
13,"(page_content, Team: White Sox\n""Payroll (millions)"": 96.92\n""Wins"": 85)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 13})"
14,"(page_content, Team: Brewers\n""Payroll (millions)"": 97.65\n""Wins"": 83)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 14})"
15,"(page_content, Team: Phillies\n""Payroll (millions)"": 174.54\n""Wins"": 81)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 15})"
16,"(page_content, Team: Diamondbacks\n""Payroll (millions)"": 74.28\n""Wins"": 81)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 16})"
17,"(page_content, Team: Pirates\n""Payroll (millions)"": 63.43\n""Wins"": 79)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 17})"
18,"(page_content, Team: Padres\n""Payroll (millions)"": 55.24\n""Wins"": 76)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 18})"
19,"(page_content, Team: Mariners\n""Payroll (millions)"": 81.97\n""Wins"": 75)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 19})"
20,"(page_content, Team: Mets\n""Payroll (millions)"": 93.35\n""Wins"": 74)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 20})"
21,"(page_content, Team: Blue Jays\n""Payroll (millions)"": 75.48\n""Wins"": 73)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 21})"
22,"(page_content, Team: Royals\n""Payroll (millions)"": 60.91\n""Wins"": 72)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 22})"
23,"(page_content, Team: Marlins\n""Payroll (millions)"": 118.07\n""Wins"": 69)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 23})"
24,"(page_content, Team: Red Sox\n""Payroll (millions)"": 173.18\n""Wins"": 69)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 24})"
25,"(page_content, Team: Indians\n""Payroll (millions)"": 78.43\n""Wins"": 68)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 25})"
26,"(page_content, Team: Twins\n""Payroll (millions)"": 94.08\n""Wins"": 66)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 26})"
27,"(page_content, Team: Rockies\n""Payroll (millions)"": 78.06\n""Wins"": 64)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 27})"
28,"(page_content, Team: Cubs\n""Payroll (millions)"": 88.19\n""Wins"": 61)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 28})"
29,"(page_content, Team: Astros\n""Payroll (millions)"": 60.65\n""Wins"": 55)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 29})"

# Customizing the CSV parsing and loading
---

Consulte la documentación del módulo csv para obtener más información sobre qué argumentos csv son compatibles.

In [15]:
loader = CSVLoader(
    file_path="../../example_data/mlb_teams_2012.csv",
    csv_args={
        "delimiter": ",",
        "quotechar": "\"",
        "fieldnames": [
            "Team",
            "Payroll (millions)",
            "Wins",
        ]
    }
)

data = loader.load()

In [16]:
print(data)

[Document(page_content='Team: Team\nPayroll (millions): "Payroll (millions)"\nWins: "Wins"', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 0}), Document(page_content='Team: Nationals\nPayroll (millions): 81.34\nWins: 98', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 1}), Document(page_content='Team: Reds\nPayroll (millions): 82.20\nWins: 97', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 2}), Document(page_content='Team: Yankees\nPayroll (millions): 197.96\nWins: 95', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 3}), Document(page_content='Team: Giants\nPayroll (millions): 117.62\nWins: 94', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 4}), Document(page_content='Team: Braves\nPayroll (millions): 83.31\nWins: 94', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 5}), Document(page_content='Team: Athletics\nPayroll (millions): 55.37\nWins: 94', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 6}), Document(page_content='Team: Rangers\nPayroll (millions): 120.51\nWins: 93', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 7}), Document(page_content='Team: Orioles\nPayroll (millions): 81.43\nWins: 93', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 8}), Document(page_content='Team: Rays\nPayroll (millions): 64.17\nWins: 90', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 9}), Document(page_content='Team: Angels\nPayroll (millions): 154.49\nWins: 89', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 10}), Document(page_content='Team: Tigers\nPayroll (millions): 132.30\nWins: 88', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 11}), Document(page_content='Team: Cardinals\nPayroll (millions): 110.30\nWins: 88', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 12}), Document(page_content='Team: Dodgers\nPayroll (millions): 95.14\nWins: 86', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 13}), Document(page_content='Team: White Sox\nPayroll (millions): 96.92\nWins: 85', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 14}), Document(page_content='Team: Brewers\nPayroll (millions): 97.65\nWins: 83', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 15}), Document(page_content='Team: Phillies\nPayroll (millions): 174.54\nWins: 81', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 16}), Document(page_content='Team: Diamondbacks\nPayroll (millions): 74.28\nWins: 81', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 17}), Document(page_content='Team: Pirates\nPayroll (millions): 63.43\nWins: 79', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 18}), Document(page_content='Team: Padres\nPayroll (millions): 55.24\nWins: 76', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 19}), Document(page_content='Team: Mariners\nPayroll (millions): 81.97\nWins: 75', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 20}), Document(page_content='Team: Mets\nPayroll (millions): 93.35\nWins: 74', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 21}), Document(page_content='Team: Blue Jays\nPayroll (millions): 75.48\nWins: 73', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 22}), Document(page_content='Team: Royals\nPayroll (millions): 60.91\nWins: 72', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 23}), Document(page_content='Team: Marlins\nPayroll (millions): 118.07\nWins: 69', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 24}), Document(page_content='Team: Red Sox\nPayroll (millions): 173.18\nWins: 69', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 25}), Document(page_content='Team: Indians\nPayroll (millions): 78.43\nWins: 68', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 26}), Document(page_content='Team: Twins\nPayroll (millions): 94.08\nWins: 66', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 27}), Document(page_content='Team: Rockies\nPayroll (millions): 78.06\nWins: 64', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 28}), Document(page_content='Team: Cubs\nPayroll (millions): 88.19\nWins: 61', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 29}), Document(page_content='Team: Astros\nPayroll (millions): 60.65\nWins: 55', metadata={'source': '../../example_data/mlb_teams_2012.csv', 'row': 30})]

In [18]:
pd.set_option("max.colwidth", None)
df = pd.DataFrame(data)
df

,0,1
0,"(page_content, Team: Team\nPayroll (millions): ""Payroll (millions)""\nWins: ""Wins"")","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 0})"
1,"(page_content, Team: Nationals\nPayroll (millions): 81.34\nWins: 98)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 1})"
2,"(page_content, Team: Reds\nPayroll (millions): 82.20\nWins: 97)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 2})"
3,"(page_content, Team: Yankees\nPayroll (millions): 197.96\nWins: 95)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 3})"
4,"(page_content, Team: Giants\nPayroll (millions): 117.62\nWins: 94)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 4})"
5,"(page_content, Team: Braves\nPayroll (millions): 83.31\nWins: 94)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 5})"
6,"(page_content, Team: Athletics\nPayroll (millions): 55.37\nWins: 94)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 6})"
7,"(page_content, Team: Rangers\nPayroll (millions): 120.51\nWins: 93)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 7})"
8,"(page_content, Team: Orioles\nPayroll (millions): 81.43\nWins: 93)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 8})"
9,"(page_content, Team: Rays\nPayroll (millions): 64.17\nWins: 90)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 9})"
10,"(page_content, Team: Angels\nPayroll (millions): 154.49\nWins: 89)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 10})"
11,"(page_content, Team: Tigers\nPayroll (millions): 132.30\nWins: 88)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 11})"
12,"(page_content, Team: Cardinals\nPayroll (millions): 110.30\nWins: 88)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 12})"
13,"(page_content, Team: Dodgers\nPayroll (millions): 95.14\nWins: 86)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 13})"
14,"(page_content, Team: White Sox\nPayroll (millions): 96.92\nWins: 85)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 14})"
15,"(page_content, Team: Brewers\nPayroll (millions): 97.65\nWins: 83)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 15})"
16,"(page_content, Team: Phillies\nPayroll (millions): 174.54\nWins: 81)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 16})"
17,"(page_content, Team: Diamondbacks\nPayroll (millions): 74.28\nWins: 81)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 17})"
18,"(page_content, Team: Pirates\nPayroll (millions): 63.43\nWins: 79)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 18})"
19,"(page_content, Team: Padres\nPayroll (millions): 55.24\nWins: 76)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 19})"
20,"(page_content, Team: Mariners\nPayroll (millions): 81.97\nWins: 75)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 20})"
21,"(page_content, Team: Mets\nPayroll (millions): 93.35\nWins: 74)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 21})"
22,"(page_content, Team: Blue Jays\nPayroll (millions): 75.48\nWins: 73)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 22})"
23,"(page_content, Team: Royals\nPayroll (millions): 60.91\nWins: 72)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 23})"
24,"(page_content, Team: Marlins\nPayroll (millions): 118.07\nWins: 69)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 24})"
25,"(page_content, Team: Red Sox\nPayroll (millions): 173.18\nWins: 69)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 25})"
26,"(page_content, Team: Indians\nPayroll (millions): 78.43\nWins: 68)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 26})"
27,"(page_content, Team: Twins\nPayroll (millions): 94.08\nWins: 66)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 27})"
28,"(page_content, Team: Rockies\nPayroll (millions): 78.06\nWins: 64)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 28})"
29,"(page_content, Team: Cubs\nPayroll (millions): 88.19\nWins: 61)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 29})"
30,"(page_content, Team: Astros\nPayroll (millions): 60.65\nWins: 55)","(metadata, {'source': '../../example_data/mlb_teams_2012.csv', 'row': 30})"